version: '3.8'

services:
  # ------------------- Sensory Receptors (C++ | Data Streams) -------------------
  sensory_receptors:
    build: 
      context: .
      dockerfile: ./sensory_receptors/Dockerfile
    container_name: sensory_receptors
    volumes:
      - ./shared_data:/shared
    environment:
      - DB_HOST=hippocampus
      - DB_PORT=5432
      - DB_NAME=rocco_commodities
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=corpus_callosum
      - NASA_FIRMS_KEY=${NASA_FIRMS_KEY}
      - AIS_API_KEY=${AIS_API_KEY}
      - OPENSKY_CLIENT_ID=${OPENSKY_CLIENT_ID}
      - OPENSKY_CLIENT_SECRET${OPENSKY_CLIENT_SECRET}

    depends_on:
      - hippocampus
      - corpus_callosum
      - ibkr_gateway
    network_mode: "service:ibkr_gateway"  
    tty: true
    restart: always

  # ----------------- Frontal Lobe (Python | AI Models + Data Analysis) ----------------
  frontal_lobe:
    build: ./frontal_lobe
    shm_size: '5gb'
    container_name: frontal_lobe
    volumes:
      - ./frontal_lobe:/app
      - ./shared_data:/shared 
    environment:
      - POSTGRES_HOST=hippocampus
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rocco_commodities
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - REDIS_HOST=corpus_callosum
      - HF_TOKEN=REMOVED
      - PYTHONUNBUFFERED=1
    depends_on:
      - hippocampus
      - corpus_callosum
    networks:
      - rocco_net
    tty: true

# ------------------- Thalamus (C++ | State + Fusion Relay) -------------------
  thalamus:
    build: 
      context: .
      dockerfile: ./thalamus/Dockerfile       
    container_name: thalamus
    environment:
      - DB_HOST=hippocampus
      - DB_NAME=rocco_commodities
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=corpus_callosum
    depends_on:
      - hippocampus
      - corpus_callosum
    networks:
      - rocco_net
    restart: always

# ------------------ Brainstem (C++ | Execution Engine) ------------------
  brainstem:
    build: 
      context: .
      dockerfile: ./brainstem/Dockerfile
    volumes:
      - ./brainstem/logs:/app/logs
      - ./common:/app/common
    container_name: brainstem
    environment:
      - REDIS_HOST=corpus_callosum
    depends_on:
      - corpus_callosum
      - ibkr_gateway
    network_mode: "service:ibkr_gateway"
    restart: always

  # ------------------ IBKR Gateway (Brokerage Access) ------------------
  ibkr_gateway:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    container_name: ibkr_gateway
    environment:
      - TWS_USERID=${TWS_USERID}       
      - TWS_PASSWORD=${TWS_PASSWORD}   
      - TRADING_MODE=paper             
      - READ_ONLY_API=false            
      - TWS_ACCEPT_INCOMING=true  
      - VNC_SERVER_PASSWORD=secure_vnc_pass
    ports:      
      - "4001:4001"  
      - "4002:4002"  
      - "5900:5900" 
    volumes:
      - ./ibkr_config/jts.ini:/home/ibgateway/Jts/jts.ini
    networks:
      - rocco_net
    restart: always

  # ----------------- Hippocampus (Postgres/gis SQL | Database) -----------------
  hippocampus:
    image: postgis/postgis:15-3.3
    container_name: hippocampus
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: rocco_commodities
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./hippocampus/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rocco_net
    ports:
      - "5432:5432"

  # ------------------ Corpus Callosum (Redis | Messaging Relay) ------------------
  corpus_callosum:
    image: redis:alpine
    container_name: corpus_callosum
    networks:
        - rocco_net

  # ------------------ Visual Cortex (Backend API & WebSocket Bridge) ------------------
  visual_cortex_backend:
    build: 
      context: ./visual_cortex/backend
    container_name: visual_cortex_backend
    environment:
      - REDIS_HOST=corpus_callosum
      - DB_HOST=hippocampus
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:                                          
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - corpus_callosum
      - hippocampus
    networks:
      - rocco_net
    ports:
      - "8000:8000"

  # ------------------ Visual Cortex (Frontend UI) ------------------
  visual_cortex_frontend:
    build: 
      context: ./visual_cortex/frontend
    container_name: visual_cortex_frontend
    environment:
      - VITE_API_URL=http://127.0.0.1:8000
    depends_on:
      - visual_cortex_backend
    networks:
      - rocco_net
    ports:
      - "3000:3000"

  # ------------------- Database Web GUI -------------------
  db_viewer:
    image: adminer
    container_name: rocco_db_viewer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - hippocampus
    networks:
      - rocco_net

  

volumes:
  postgres_data:

networks:
  rocco_net:
    driver: bridge